---
title: Week 1 - Statistics Review
sitetitle: Week 1
summary: Here we describe how to add a page to your site.

date: "2020-08-19"
start_date: "2020-08-31"
end_date: "2020-09-04"
menu:
  content:
    parent: Course content
    weight: 1
  
  # Academic page type (do not modify).
type: docs
output:
  blogdown::html_page:
    toc: true

## Slides

pdf: /slides/ch02-slides.pdf
thumb: /slides/ch02-slides.png

# Position of this page in the menu. Remove this option to sort alphabetically.
weight: 1

---




Welcome to Week 1! Our goal this week is to (1) help us sort out our varying technologies and workflows and (2) review some statistics! Basically, this is week 1 of a two-week mini-bootcamp to get us ready for the glorious world of regressions!

I'll ask you to self sort: 

- **I took EC170/STAT141 recently and remember some stuff:** Read through SW, and dig deeper into anything that doesn't look familiar. Watch the class videos. Use the Khan Academy to clarify anything you feel a bit fuzzy on. Make sure you can do the practice problems. 
- **Everyone else** Start by reviewing the Khan Academy concepts. Work through *all* their practice problems. Then head into our EC200 practice problems. 


## Topics 

- Probability distributions 
	- SW Chapter 2.2
	- Discrete probability distributions 
	- Continuous probability distributions 
	
- Hypothesis testing 
	- SW Chapter 2.2
	- <i class="fas fa-tv">  </i>[Khan Academy - Significance Testing](https://www.khanacademy.org/math/ap-statistics/tests-significance-ap)
	- <i class="fas fa-tv">  </i>[Khan Academy - Significance Testing](https://www.khanacademy.org/math/ap-statistics/tests-significance-ap)

## Slides

`r blogdown::shortcode("slides")`

## Videos

