

---
title: Week 5 - Inference with One Regressor
sitetitle: Week 5
summary: "EC200 - Week 5 Inference (CH5)"

date: "2020-09-16"
start_date: "2020-09-28"
end_date: "2020-10-02"

  
  # Academic page type (do not modify).
type: docs
menu:
  content:
    parent: Course content
    weight: 5
    
output:
  blogdown::html_page:
    toc: true

pdf: /slides/ch5-slides.pdf
thumb: /slides/ch5-slides.png



---

## Overview

As we carry on into the wonderful world of statistical inference, expect flashbacks of our statistics review. That's what the review was for! It's all coming together  :relieved:.

## Reading Guide

**Chapter 5: Hypothesis Tests and Confidence Intervals**

**5.1**	Testing Hypotheses About One of the Regression Coefficients
This is very important stuff. Again, don’t worry about calculating the variance of a beta coefficient by hand. However, note how similar this is to our hypothesis testing in Chapter 3!

**5.2**	Confidence intervals for a regression coefficient

**5.3**	Regression when X is a binary variable 
	We are going to use this ALL THE TIME. 

**5.4**	Heteroskedasticity and homoskedasticity 
Drop "heteroskedasticity" into any conversation and you're sure to delight. Just one more benefit of EC200. 
The examples and implications of heteroskedasticity are important. And now you'll know to add `, robust` to all your Stata regressions.
 

**5.5**	Theoretical foundations of OLS
	Know the Gauss-Markov theorem and related assumptions. Skip "regression estimators other than OLS." The appendix contains a proof of the Gauss-Markov theorm, but we will not cover that.

~~**5.6**~~ Skip this section!

**5.7**	Conclusion

## Slides

`r blogdown::shortcode("slides")`

## Videos
### [Video: Inference with One-Variable Linear Regression](https://youtu.be/DZo5m5q3bmA)
`r htmltools::HTML("{{< youtube DZo5m5q3bmA >}}")`


