---
title: "Research Paper: Final Submission"
linktitle: "07 Final"
date: "2020-06-22"
due_date: "2020-12-08"
due_time: "11:59 PM"
menu:
  assignment:
    parent: Research Paper
    weight: 30
type: docs
editor_options: 
  chunk_output_type: console
output:
  blogdown::html_page:
    toc: true
---

## Research Paper - Final Submission 


Research papers are fairly formulaic, and that's a good thing - it helps readers know where to look for information, depending on what they want to get out of it. 


## What should I submit? 

Your paper is due at **11:59pm December 08**. *I cannot accept extensions*, as there are external grading deadlines I need to meet. 

You should submit the following: 

 - Final paper in pdf or docx format 
 - Stata do-file with all analysis you conducted 
 - Stata log file with results for analysis conducted in your do-file. 
 
I will grade your papers following the rubric. If you would like me to share comments, you must *opt-in* by filling out the [feedback survey](https://forms.gle/kxGcNvFzzGtduGQ99). If you do not fill it out, you will not receive feedback! 


## Elements of your research paper 

A reasonable approach is to pull up an academic paper you're citing that is in the economics literature and see how it's structured. However, here is more general guide. While a good paper
will meet these criteria, please note that, this is not a grading
rubric!



### General/Style

-   First-person active voice! (I estimate a regression, **NOT** "A
    regression is estimated")

    -   Single-authored paper first person singular, "I." (You're not
        the queen!)

    -   Joint-authored paper first person plural, "we."

    -   Don't believe me? Check out any economics paper published in the
        past 20 years. There's *some* variation in I vs. we, but *all*
        use active voice.

-   Paper written in present tense

-   Paper divided into numbered, labeled sections.

-   A research paper is not an essay!

    -   Personal opinions don't have a place

    -   Sources should be primarily academic (peer-reviewed journals,
        working papers, etc.), maybe some non-academic sources for
        motivation only

    -   Clear, labeled sections



### Abstract & Title

You'll need a title *and an abstract*

-   Descriptive title

-   Abstract that summarizes the paper and findings in 200 words or less


### Introduction 

In an economics paper, and introduction stands alone! That is, a tired person could read the introduction and understand what you did, what you found, and why it matters. Our papers are not mystery novels - there's no need for a plot twist on page 8! 

I'm a big fan of the [introduction formula](http://blogs.ubc.ca/khead/research/research-advice/formula), which is written for folks writing a longer academic paper, but the principles are still solid. 


#### Guidelines and structure

-   Introduction reads like an academic article. Motivates, describes
    what you do and what you find. (Almost like a mini-paper!)

    -   Reader can infer all main points of paper just from introduction

-   States your research question clearly

-   Explains what economic theory says about the potential answers to
    your questions, and/or defines clear hypotheses that you test

-   Describes why your topic is important

-   Describes what you do

-   Describes what you find

-   Describe how it contributes to knowledge




### Motivation or Background or Literature Review**

-   What you include here depends on topic. Sometimes the reader needs
    to know how your question links to economic theory. Sometimes it's
    more important to know specific context first, and then to turn to
    the literature. Sometimes it's most important to summarize what the
    literature already knows. Your call.

-   At the back of your mind, when motivating your paper, ask "what is
    the link to economics"?

    -   If studying discrimination, what does economic theory tell us
        about why discrimination exists/persists

    -   If studying stock market returns, what do economic models tell
        us about our ability to predict returns?

-   Includes papers that have answered your research question (or
    similar research questions)

-   Research results described in present tense ("Smith finds," not
    "Smith found")

-   Papers are put in context. That is, rather than just listing paper A
    and finding, paper B and finding, etc, you link each one (or group)
    to their contribution (as relates to your research question)

### Methodology/Data**

-   Describe the data you use, where did it come from? If you didn't
    create it, cite it

-   Population model written out

    - If you're using Word, use equation editor. Make it look nice.
    - Don't forget the error term!
    - Use proper equation notation ($\beta$, $u$, etc)
    - Use appropriate subscripts (*$$i, $t$, $y$, etc)*
    - All relevant variables explained/defined
    - Use "real names" to describe variables when possible (ie use
        $female$ for women, not $w1$)
    - Make sure your variables are written correctly - an equation like $wage = \alpha_0 + \alpha_1 race$ doesn't make sense - race isn't continuous! 
    - If you are using a lot of categorical variables and find it awkward to write them out, you can simplify: 
      - Showing that you have state fixed effects: $... + f_s + $ and the in the text, "where $f_s$ is a vector of state fixed effects"
      - Including a set of occupational dummy variables $\sum^K_{k=1}\delta_kD_k$, "where $D_k$ is a dummy variable for occupation $k$, from $k \in [1,K]$" (or something in that general spirit)
  
-   Describe your methodology. Are you estimating a model using OLS? If
    so, say so.

-   Clarify whether we are looking at causal estimates or something
    else. What are the estimated parameters of interest. What do they
    mean?

-   Correct standard errors: robust? Clustered? Something else?

### Results**

-   When using categorical/dummy variables, what is your omitted
    category? Make sure you know and that it's clear.

-   What are the units of your measures?

    -   Is that percent or percentage points?

-   Discuss using a reasonable number of decimal places (usually only 1
    or 2)

### Limitations or Discussion**

-   Include as a separate section or integrate into results

-   What might us from making causal interpretations about our
    coefficient of interest?

    -   Omitted variable bias?

    -   Reverse causality?

    -   Measurement error?

-   Are the results externally valid?

-   What other considerations are important?

### Conclusion**

-   Brief summary of paper

-   Limitations (summary of limitations/discussion section)

-   Implications for policy

-   Implications for future research

### Tables and Figures**

-   Tables should be properly formatted. That is, they should be made in
    Excel (or LaTeX) and NEVER copied and pasted out of Stata

-   Variables should be described using real words. Ie, "number of
    children," not "numchld."

-   Tables and figures should be numbered (Table 1, Table 2, etc...
    Figure 1, Figure 2, etc.) and should also be given a title. Refer to
    tables by their numbers in the text.

-   Regression tables include standard errors. Use stars to indicate
    statistical significance. (The Stata package outreg2 is a big help!)

-   In most contexts, about 3 places past the decimal point is right,
    but it depends on the magnitudes. If you really want to be precise,
    set and stick to a reasonable number of significant digits. There's
    no place for a number like 0.05403823 or 0.0000000 in your tables.

### References**

-   Use footnotes rather than endnotes

-   At the end of your paper, include list of references cited

-   You can format using APA, MLA, or Chicago style

    -   Citation Owl or Google Scholar will do it for you

-   In-text, cite with author and year (Author, Year; Author, Year) or
    (Author Year, Author Year)

### Working with data**

-   What is the unit of observation? Is it people, households, states,
    etc? Make sure the unit is appropriate to your question

#### If you're working with individual-level data...*

-   What is the age range you want in your sample?

-   What years of data do you need?

-   If in the US, do you want citizens, or do you also want to include
    immigrants?

-   If dealing with labor force variables, do you want all people of
    working age, all those who are in the labor force, or all who are
    employed?
